export interface Project {
  id: number; // Or string/UUID if preferred, but number is simpler for local SQLite
  name: string;
  description?: string; // Optional description for the ebook project
  parameters?: string; // Store parameters as JSON string
  createdAt: string; // ISO 8601 date string
  updatedAt: string; // ISO 8601 date string
}

export interface Chapter {
  id: number;
  projectId: number; // Foreign key to Project
  title: string;
  description: string; // Short description generated by LLM or user
  content?: string; // Full chapter text generated by LLM
  order: number; // To maintain chapter sequence
  createdAt: string;
  updatedAt: string;
}

// Interface for parameters (stored as JSON in the project table)
export interface EbookParameters {
  genre?: string;
  targetAudience?: string;
  style?: string;
  tone?: string;
  chapterLength?: 'Short' | 'Medium' | 'Long' | string; // Allow predefined or custom string
  pointOfView?: 'First Person' | 'Third Person Limited' | 'Third Person Omniscient' | string;
  customInstructions?: string;
  continueNarrative?: boolean; // NEW: Flag to include previous chapter context
  narrativeHooks?: string; // NEW: Recurring elements/jokes (e.g., newline-separated)
  // Add other relevant parameters as needed
}

// Interface for chat messages
export interface ChatMessage {
  id: number;
  projectId: number; // Link message to a project
  chapterId?: number; // Optional: Link message to a specific chapter context
  role: 'user' | 'assistant' | 'system'; // Role of the message sender
  content: string; // The message text
  createdAt: string; // Timestamp
}

// Interface for the JSON export structure
export interface EbookProjectExport {
  name: string;
  description?: string;
  parameters?: EbookParameters;
  chapters: Omit<Chapter, 'projectId' | 'id' | 'createdAt' | 'updatedAt'>[]; // Export chapters without DB-specific fields
  // Optionally include chat messages if needed in the export
  // chatMessages?: Omit<ChatMessage, 'projectId' | 'id' | 'createdAt'>[];
}
